name: Deploy To Prod / Release

on: 
  workflow_dispatch:
    inputs: 
      packageName:
        description: 'Package Name'     
        required: true
        default: 'BuyHandset'  
jobs:
  createVersion:
    runs-on: ubuntu-latest
    container:
      image: jfgarcia268/sfdx_vlocity_java:v13.0
    steps:  
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Salesforce Package  
      run: |
        echo ${{ secrets.SFDX_URL_DEVHUB }}   > env.sfdx
        sfdx force:auth:sfdxurl:store -d -a DEVHUB -f env.sfdx
        #Get latest PackageVersion from DevHub and create file "PID.txt" with it
        if [ -f rm PID.txt  ]; then
          rm rm PID.txt  
        fi
        ./Get_Latest_Version_Package.sh DEVHUB ${{ github.event.inputs.packageName }}
        PACKAGE_ID=$(cat PID.txt)
        echo "PACKAGE_ID:${PACKAGE_ID}"
        sfdx force:package:version:promote --noprompt --package ${PACKAGE_ID} --targetdevhubusername DEVHUB
        sfdx force:package:install --package ${PACKAGE_ID} --targetusername=DEVHUB --wait 1000 --publishwait 1000 --securitytype=AdminsOnly -k ${{ secrets.KEY }}
        sfdx force:user:permset:assign --targetusername DEVHUB --permsetname HandsetBuy || true
    - name: Deploy Vlocity  
      run: |
        echo ${{ secrets.SFDX_URL_DEVHUB }}   > env.sfdx
        sfdx force:auth:sfdxurl:store -d -a DEVHUB -f env.sfdx
        vlocity -sfdx.username DEVHUB -job Deploy_Delta.yaml packDeploy --verbose true --simpleLogging true
        vlocity -sfdx.username DEVHUB --nojob runApex -apex apex/RunProductBatchJobs.cls --verbose true --simpleLogging true
